### ISSUE TITLE
krb5i/p mounting hang on z/OS NFS client

### ISSUE THREAD

**Issue by skmprabhu1** [nfs-ganesha/ntirpc#248]
The ganesha hang with below stack .. 

(gdb) bt
#0  0x000003ffa2b118e8 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x000003ffa2b0a9d4 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x000003ffa31cfeaa in svcauth_gss_wrap (req=0x3ff6c0027c0, xdrs=0x3ff6c00dad0)
    at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_auth_gss.c:779
#3  0x000003ffa31bb87a in svc_vc_reply (req=0x3ff6c0027c0) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_vc.c:960
#4  0x000003ffa31ad03c in svc_sendreply (req=0x3ff6c0027c0) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc.c:507
#5  0x000003ffa31cf732 in _svcauth_gss (req=0x3ff6c0027c0, no_dispatch=0x3ff9f1f1e9f)
    at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_auth_gss.c:591
#6  0x000003ffa31ad6e0 in svc_auth_authenticate (req=0x3ff6c0027c0, no_dispatch=0x3ff9f1f1e9f)
    at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_auth.c:99
#7  0x000003ffa32670ca in nfs_rpc_process_request (reqdata=0x3ff6c0027c0)
    at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/MainNFSD/nfs_worker_thread.c:887
#8  0x000003ffa326a01e in nfs_rpc_valid_NFS (req=0x3ff6c0027c0) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/MainNFSD/nfs_worker_thread.c:1625
#9  0x000003ffa31bb5fc in svc_vc_decode (req=0x3ff6c0027c0) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_vc.c:906
#10 0x000003ffa31b5ff2 in svc_request (xprt=0x3ff80001620, xdrs=0x3ff6c0013d0)
    at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_rqst.c:1202
#11 0x000003ffa31bb4bc in svc_vc_recv (xprt=0x3ff80001620) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_vc.c:879
#12 0x000003ffa31b5f4e in svc_rqst_xprt_task_recv (wpe=0x3ff80001858)
    at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_rqst.c:1183
#13 0x000003ffa31b6e70 in svc_rqst_epoll_loop (wpe=0x20d57fe8) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/svc_rqst.c:1564
#14 0x000003ffa31c5650 in work_pool_thread (arg=0x3ff84000b60) at /usr/src/debug/gpfs.nfs-ganesha-3.5-ibm070.11.el8.s390x/libntirpc/src/work_pool.c:184
#15 0x000003ffa2b080b6 in start_thread () from /lib64/libpthread.so.0
#16 0x000003ffa287bd3e in thread_start () from /lib64/libc.so.6

The thread is waiting for gd->lock , but it is already taken by same thread in _svcauth_gss ().

This issue was injected by below commit ..
================================
commit 5a02a887755b4f7f6ce12902543fb976bd98c8e5
Author: Sriram Patil <sriramp@vmware.com>
Date:   Thu Jan 30 16:56:24 2020 -0800

    Fixing the race condition when caching GSS contexts

    GSS_DATA and GSS_DESTROY requests expect the context is prensent in the
    cache, otherwise it returns RPCSEC_GSS_CREDPROBLEM. The GSS context is
    established and cached in GSS_INIT/GSS_CONTINUE_INIT requests. NTIRPC
    sends a reply back to the client before inserting the context in cache.
    This fix addresses the race and makes sure that the GSS context is
    inserted before sending the response to client.

    Signed-off-by: Sriram Patil <sriramp@vmware.com>
    (cherry picked from commit 5716b42f91a9850d722d83a4b5a695f096d68101)
================================

Above fix moved below condition just before calling svc_sendreply()

    581                 if (gr.gr_major == GSS_S_COMPLETE) {
    **582                         gd->established = true;**
    583                         (void)authgss_ctx_hash_set(gd);
    584                 }

and svc_sendreply() -> svc_vc_reply() -> svcauth_gss_wrap().

    776         if (!gd->established || gc->gc_svc == RPCSEC_GSS_SVC_NONE) <<<<<<<<<<  z/OS NFS client sends gc->svc= rpcsec_gss_svc_integrity. But linux sends RPCSEC_GSS_SVC_NONE. 
    777                 return (svc_auth_none.svc_ah_ops->svc_ah_wrap(req, xdrs));
    778
    779         mutex_lock(&gd->lock); 

Before the patch,  gd->established was not set,  so returned in line#777. 
But the patch set gd->established=true,  so continued and hit deadlock!!!!!

JFYI, Here is the difference between NFS4 null request between linux and Z/OS ( during mount request)
Linux,
       GSS Procedure: RPCSEC_GSS_INIT (1)
       GSS Service: rpcsec_gss_svc_none (2)

Z/OS,
       GSS Procedure: RPCSEC_GSS_INIT (1)
       GSS Service: rpcsec_gss_svc_integrity (2)

**Comment by skmprabhu1** [comment]
Created pull request 
https://github.com/nfs-ganesha/ntirpc/pull/249

**Comment by skmprabhu1** [comment]
Fixed
